#!/bin/bash

set -euo pipefail
HERE=$(cd $(dirname $0); pwd)

bwrap \
  --ro-bind / / \
  --dev /dev \
  --proc /proc \
  --tmpfs /tmp \
  --tmpfs /run \
  --bind "$HERE" "$HERE" \
  --die-with-parent \
  --new-session \
  saa "$@"
